
function selectActivity(id){_actSelected=id;document.querySelectorAll('[id^="act-"]').forEach(function(b){b.style.borderColor='var(--border)';b.style.background='var(--card)';b.style.color='var(--txt2)';});var el=document.getElementById('act-'+id);if(el){el.style.borderColor='var(--purple)';el.style.background='rgba(163,113,247,0.12)';el.style.color='var(--purple)';}}
function selectAFeeling(f){window._aFeeling=f;document.querySelectorAll('[id^="af-"]').forEach(function(b){b.classList.remove('selected');});var el=document.getElementById('af-'+f);if(el)el.classList.add('selected');}
function actStep(d){var i=document.getElementById('act-dur');if(i)i.value=Math.max(5,(+i.value||30)+d);}
function saveActivity(){if(!_actSelected){toast('Selecione uma atividade',false);return;}var act=ACTIVITIES.find(function(a){return a.id===_actSelected;});var dur=+((document.getElementById('act-dur')||{}).value)||30,notes=(document.getElementById('act-notes')||{}).value||'',date=(document.getElementById('act-date')||{}).value||new Date().toISOString().split('T')[0];saveSession({id:uid(),type:'activity',workoutName:act.ico+' '+act.name,date:new Date(date+'T12:00:00').toISOString(),duration:dur,notes:notes,feeling:window._aFeeling,exercises:[]});toast('\uD83C\uDFC3 Atividade salva!');setTimeout(function(){showPage('history');},700);}


// PART 5: Workouts page, Profile, Suggest, Theme, Boot
var editingWoId=null;
function renderWorkouts(){
  editingWoId=null;
  document.getElementById('wk-title').textContent='Treinos';
  document.getElementById('wk-sub').textContent='Gerencie seus treinos';
  var wks=getWorkouts(),emojis=['\uD83D\uDCAA','\uD83D\uDD25','\u26A1','\uD83C\uDFAF'];
  document.getElementById('wk-body').innerHTML='<div style="display:flex;flex-direction:column;gap:10px;margin-bottom:16px">'+wks.map(function(w,i){return'<div class="card" style="padding:16px"><div style="display:flex;align-items:center;gap:12px;margin-bottom:10px"><span style="font-size:28px">'+emojis[i%emojis.length]+'</span><div style="flex:1"><div style="font-weight:700;font-size:17px">'+esc(w.name)+'</div><p style="font-size:13px;color:var(--muted)">'+(w.exercises||[]).length+' exerc\u00EDcios</p></div></div><div style="display:flex;gap:8px"><button class="btn btn-blue btn-sm" style="flex:1" onclick="homeEditExercises(\''+w.id+'\')">\u270F\uFE0F Editar</button><button class="btn btn-ghost btn-sm" style="flex:1" onclick="homeDupWorkout(\''+w.id+'\')">\uD83D\uDCCB Copiar</button><button class="btn btn-danger btn-sm" style="width:44px;padding:8px" onclick="homeDelWorkout(\''+w.id+'\')">\uD83D\uDDD1</button></div></div>';}).join('')+'</div>'
    +'<button class="btn btn-blue" onclick="homeAddWorkout()">+ Criar Novo Treino</button>'
    +'<div style="margin-top:24px"><p class="lbl" style="margin-bottom:10px">Backup</p><div style="display:flex;gap:8px"><button class="btn btn-ghost btn-sm" style="flex:1" onclick="doExport()">\uD83D\uDCE4 Exportar</button><label class="btn btn-ghost btn-sm" style="flex:1;cursor:pointer">\uD83D\uDCE5 Importar<input type="file" accept=".json" style="display:none" onchange="doImport(this)"></label></div></div>';
}
function doExport(){var data={workouts:getWorkouts(),history:getHistory(),weightHistory:getWeights(),at:new Date().toISOString()};var a=document.createElement('a');a.href='data:application/json,'+encodeURIComponent(JSON.stringify(data,null,2));a.download='gymtracker-'+(CURRENT_USER||'user')+'-'+new Date().toISOString().split('T')[0]+'.json';a.click();toast('\uD83D\uDCE4 Exportado!');}
function doImport(input){var f=input.files[0];if(!f)return;var r=new FileReader();r.onload=function(e){try{var d=JSON.parse(e.target.result);if(d.workouts)saveWorkouts(d.workouts);if(d.history)lss(KEYS.H,d.history);if(d.weightHistory)lss(KEYS.WH,d.weightHistory);toast('\u2705 Importado!');renderWorkouts();}catch(err){toast('\u274C Erro ao importar',false);}};r.readAsText(f);}

var PROFILE_KEY='gt_profile_v1',WEIGHT_LOG_KEY='gt_weightlog_v1';
function getProfile(){return ls(PROFILE_KEY)||{name:'',photo:'',weight:'',height:'',goal:'hypertrophy',birthdate:''};}
function saveProfile(p){lss(PROFILE_KEY,p);}
function getWeightLog(){return ls(WEIGHT_LOG_KEY)||[];}
function addWeightLog(w){var log=getWeightLog();log.push({date:new Date().toISOString(),weight:w});lss(WEIGHT_LOG_KEY,log);}

function imcColor(v){v=parseFloat(v);return v<18.5?'#1d4ed8':v<25?'#15803d':v<30?'#d97706':'#dc2626';}
function imcLabel(v){v=parseFloat(v);return v<18.5?'Abaixo do peso':v<25?'Peso normal':v<30?'Sobrepeso':'Obesidade';}
function imcEmoji(v){v=parseFloat(v);return v<18.5?'\u26A0\uFE0F':v<25?'\u2705':v<30?'\u26A1':'\uD83D\uDD34';}
function loadProfilePhoto(input){var f=input.files[0];if(!f)return;var r=new FileReader();r.onload=function(e){saveProfileField('photo',e.target.result);renderProfile();};r.readAsDataURL(f);}
function saveProfileField(field,val){var p=getProfile();p[field]=val;saveProfile(p);if(['birthdate','weight','height','photo'].includes(field))renderProfile();}
function profileStep(field,delta){var p=getProfile();var v=parseFloat(p[field]||0)+delta;if(v<0)v=0;p[field]=v;saveProfile(p);var inp=document.getElementById('pf-'+field);if(inp)inp.value=v;if(field==='weight'||field==='height')renderProfile();}
function logWeightNow(){var inp=document.getElementById('new-weight');var v=parseFloat(inp&&inp.value);if(!v||v<=0)return;addWeightLog(v);saveProfileField('weight',v);inp.value='';toast('\u2696\uFE0F Peso registrado!');renderProfile();}

function renderProfile(){
  var p=getProfile(),log=getWeightLog(),age='';
  if(p.birthdate){var bd=new Date(p.birthdate),now=new Date();age=Math.floor((now-bd)/(365.25*24*3600*1000));}
  var imc='';if(p.weight&&p.height){var h=parseFloat(p.height)/100;imc=(parseFloat(p.weight)/(h*h)).toFixed(1);}
  var photoHtml=p.photo?'<img src="'+p.photo+'" style="width:100%;height:100%;object-fit:cover;border-radius:50%"/>':'<span style="font-size:48px">\uD83D\uDC64</span>';
  var goalLabels={hypertrophy:'\uD83D\uDCAA Hipertrofia',loss:'\uD83D\uDD25 Emagrecimento',endurance:'\uD83C\uDFC3 Resist\u00EAncia',health:'\u2764\uFE0F Sa\u00FAde Geral',strength:'\uD83C\uDFCB\uFE0F For\u00E7a'};
  document.getElementById('profile-sub').textContent=p.name||CURRENT_USER||'Seu perfil';
  var logHtml='';
  if(log.length>1){var maxW=Math.max.apply(null,log.map(function(l){return l.weight;})),minW=Math.min.apply(null,log.map(function(l){return l.weight;})),range=maxW-minW||1,last10=log.slice(-10);logHtml='<div style="display:flex;align-items:flex-end;gap:4px;height:80px;margin-top:10px">'+last10.map(function(l,i){var pct=(l.weight-minW)/range*80+10,isLast=i===last10.length-1;return'<div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:2px"><div style="width:100%;height:'+pct+'%;background:'+(isLast?'var(--blue)':'var(--border)')+';border-radius:3px 3px 0 0;min-height:4px"></div><div style="font-size:9px;color:var(--muted)">'+l.weight+'</div></div>';}).join('')+'</div>';}
  document.getElementById('profile-body').innerHTML=
    '<div style="display:flex;flex-direction:column;align-items:center;gap:12px;padding:20px;background:var(--card);border:1px solid var(--border);border-radius:var(--rl);margin-bottom:16px"><div style="position:relative"><div style="width:100px;height:100px;border-radius:50%;background:var(--bg2);border:3px solid var(--border);overflow:hidden;display:flex;align-items:center;justify-content:center">'+photoHtml+'</div><label style="position:absolute;bottom:0;right:0;width:30px;height:30px;border-radius:50%;background:var(--blue);display:flex;align-items:center;justify-content:center;cursor:pointer;font-size:14px;border:2px solid var(--bg2)">\uD83D\uDCF7<input type="file" accept="image/*" style="display:none" onchange="loadProfilePhoto(this)"></label></div><div style="text-align:center"><input id="pf-name" value="'+esc(p.name)+'" placeholder="Seu nome" style="font-family:var(--fd);font-size:22px;background:transparent;border:none;border-bottom:1px solid var(--border);border-radius:0;text-align:center;color:var(--txt);width:220px;outline:none" oninput="saveProfileField(\'name\',this.value)"/>'+(age?'<p style="font-size:13px;color:var(--txt2);margin-top:4px">'+age+' anos</p>':'')+'<p style="font-size:12px;color:var(--muted);margin-top:4px">@'+esc(CURRENT_USER||'')+'</p></div></div>'
    +(imc?'<div style="background:'+imcColor(imc)+';border-radius:var(--r);padding:10px 16px;margin-bottom:16px;display:flex;align-items:center;justify-content:space-between"><div><div style="font-size:12px;color:rgba(255,255,255,0.8)">IMC</div><div style="font-family:var(--fd);font-size:28px;color:#fff">'+imc+'</div><div style="font-size:11px;color:rgba(255,255,255,0.9)">'+imcLabel(imc)+'</div></div><span style="font-size:40px">'+imcEmoji(imc)+'</span></div>':'')
    +'<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:16px"><div><span class="lbl">Peso atual (kg)</span><div class="ngrp"><button class="sbtn" onclick="profileStep(\'weight\',-0.5)">-</button><input type="number" id="pf-weight" value="'+esc(p.weight)+'" step="0.5" placeholder="70" oninput="saveProfileField(\'weight\',this.value)" style="text-align:center"/><button class="sbtn" onclick="profileStep(\'weight\',0.5)">+</button></div></div><div><span class="lbl">Altura (cm)</span><div class="ngrp"><button class="sbtn" onclick="profileStep(\'height\',-1)">-</button><input type="number" id="pf-height" value="'+esc(p.height)+'" placeholder="170" oninput="saveProfileField(\'height\',this.value)" style="text-align:center"/><button class="sbtn" onclick="profileStep(\'height\',1)">+</button></div></div></div>'
    +'<div style="margin-bottom:16px"><span class="lbl">Data de Nascimento</span><input type="date" id="pf-bday" value="'+esc(p.birthdate)+'" oninput="saveProfileField(\'birthdate\',this.value)"/></div>'
    +'<div style="margin-bottom:16px"><span class="lbl">Objetivo</span><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">'+Object.entries(goalLabels).map(function(e){return'<button onclick="saveProfileField(\'goal\',\''+e[0]+'\');renderProfile()" style="padding:10px;border-radius:var(--r);border:2px solid '+(p.goal===e[0]?'var(--blue)':'var(--border)')+';background:'+(p.goal===e[0]?'var(--bluedim)':'var(--card)')+';color:'+(p.goal===e[0]?'var(--blue2)':'var(--txt2)')+';font-family:var(--fb);font-size:13px;font-weight:600;cursor:pointer">'+e[1]+'</button>';}).join('')+'</div></div>'
    +'<div style="background:var(--card);border:1px solid var(--border);border-radius:var(--rl);padding:16px;margin-bottom:16px"><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px"><p style="font-weight:700;font-size:15px">\uD83D\uDCCA Hist\u00F3rico de Peso</p>'+(log.length?'<span style="font-size:13px;color:var(--txt2)">'+log.length+' registros</span>':'')+'</div>'
    +(log.length?'<div style="display:flex;gap:16px;margin-bottom:8px"><div style="text-align:center"><div style="font-family:var(--fd);font-size:24px;color:var(--blue2)">'+log[log.length-1].weight+'</div><div style="font-size:11px;color:var(--muted)">Atual</div></div>'+(log.length>1?'<div style="text-align:center"><div style="font-family:var(--fd);font-size:24px;color:'+((log[log.length-1].weight-log[0].weight)<=0?'var(--green)':'var(--red)')+'">'+((log[log.length-1].weight-log[0].weight)>0?'+':'')+(log[log.length-1].weight-log[0].weight).toFixed(1)+'</div><div style="font-size:11px;color:var(--muted)">Varia\u00E7\u00E3o</div></div>':'')+'</div>'+logHtml:'<p style="font-size:13px;color:var(--muted)">Nenhum registro ainda.</p>')
    +'<div style="display:flex;gap:8px;margin-top:14px"><input type="number" id="new-weight" step="0.1" placeholder="Peso de hoje (kg)" style="flex:1"/><button onclick="logWeightNow()" class="btn btn-blue" style="width:auto;padding:10px 16px;min-height:44px;font-size:14px">+ Registrar</button></div></div>'
    +'<button class="btn btn-ghost" onclick="showPage(\'workouts\')" style="font-size:14px">\u2699\uFE0F Gerenciar Treinos</button>'
    +'<div style="height:16px"></div>'
    +'<button class="btn btn-ghost" onclick="openThemePicker()" style="font-size:14px">\uD83C\uDFA8 Personalizar Tema</button>'
    +'<div style="height:16px"></div>'
    +'<button class="btn btn-danger" onclick="authShowSwitcher()" style="font-size:14px">\uD83D\uDC64 Trocar / Sair da conta</button>';
}

var SUGGEST_FILTER='all';
var WORKOUT_LIBRARY=[
  {id:'sl1',category:'hypertrophy',level:'beginner',name:'Iniciante Full Body A',days:'3x/semana',goal:'\uD83D\uDCAA Hipertrofia',exercises:[{name:'Agachamento',sets:3,reps:10},{name:'Supino',sets:3,reps:10},{name:'Remada',sets:3,reps:10},{name:'Shoulder Press',sets:3,reps:10},{name:'B\u00EDceps Curl',sets:3,reps:12},{name:'Tr\u00EDceps na Corda',sets:3,reps:12},{name:'Abdominal',sets:3,reps:15}]},
  {id:'sl2',category:'hypertrophy',level:'intermediate',name:'Push Pull Legs - Push',days:'6x/semana',goal:'\uD83D\uDCAA Hipertrofia',exercises:[{name:'Supino',sets:4,reps:8},{name:'Shoulder Press',sets:4,reps:8},{name:'Pec Deck',sets:3,reps:12},{name:'Eleva\u00E7\u00E3o Frontal',sets:3,reps:12},{name:'Lateral Raise',sets:3,reps:15},{name:'Tr\u00EDceps na Corda',sets:4,reps:12},{name:'Pullover',sets:3,reps:12}]},
  {id:'sl3',category:'hypertrophy',level:'intermediate',name:'Push Pull Legs - Pull',days:'6x/semana',goal:'\uD83D\uDCAA Hipertrofia',exercises:[{name:'Remada',sets:4,reps:8},{name:'Lat Pulldown',sets:4,reps:10},{name:'Face Pull',sets:3,reps:15},{name:'Rosca Direta',sets:4,reps:10},{name:'Rosca Martelo',sets:3,reps:12},{name:'Abdominal',sets:3,reps:20}]},
  {id:'sl4',category:'hypertrophy',level:'intermediate',name:'Push Pull Legs - Legs',days:'6x/semana',goal:'\uD83D\uDCAA Hipertrofia',exercises:[{name:'Agachamento',sets:4,reps:8},{name:'Leg Press',sets:4,reps:10},{name:'Leg Extension',sets:3,reps:12},{name:'Seated Leg Curl',sets:3,reps:12},{name:'Hip Adductor',sets:3,reps:15},{name:'Calf Raise',sets:4,reps:15},{name:'Afundo',sets:3,reps:10}]},
  {id:'sl5',category:'loss',level:'beginner',name:'Circuito Queima de Gordura',days:'4x/semana',goal:'\uD83D\uDD25 Emagrecimento',exercises:[{name:'Agachamento',sets:4,reps:15},{name:'Supino',sets:4,reps:15},{name:'Remada',sets:4,reps:15},{name:'Shoulder Press',sets:3,reps:15},{name:'Abdominal',sets:4,reps:20},{name:'Stiff',sets:3,reps:15}]},
  {id:'sl6',category:'loss',level:'intermediate',name:'HIIT Funcional',days:'4x/semana',goal:'\uD83D\uDD25 Emagrecimento',exercises:[{name:'Agachamento',sets:5,reps:20},{name:'Afundo',sets:4,reps:15},{name:'Abdominal',sets:5,reps:25},{name:'Shoulder Press',sets:4,reps:15},{name:'Remada',sets:4,reps:15}]},
  {id:'sl7',category:'strength',level:'intermediate',name:'For\u00E7a - M\u00E9todo 5x5',days:'3x/semana',goal:'\uD83C\uDFCB\uFE0F For\u00E7a',exercises:[{name:'Agachamento',sets:5,reps:5},{name:'Supino',sets:5,reps:5},{name:'Remada',sets:5,reps:5},{name:'Shoulder Press',sets:5,reps:5},{name:'Stiff',sets:5,reps:5}]},
  {id:'sl8',category:'strength',level:'advanced',name:'For\u00E7a - Powerlifting Base',days:'4x/semana',goal:'\uD83C\uDFCB\uFE0F For\u00E7a',exercises:[{name:'Agachamento',sets:5,reps:3},{name:'Supino',sets:5,reps:3},{name:'Stiff',sets:4,reps:5},{name:'Remada',sets:4,reps:6},{name:'Shoulder Press',sets:4,reps:5},{name:'Abdominal',sets:4,reps:15}]},
  {id:'sl9',category:'endurance',level:'beginner',name:'Resist\u00EAncia Muscular',days:'3x/semana',goal:'\uD83C\uDFC3 Resist\u00EAncia',exercises:[{name:'Agachamento',sets:3,reps:20},{name:'Supino',sets:3,reps:20},{name:'Remada',sets:3,reps:20},{name:'Lat Pulldown',sets:3,reps:20},{name:'Shoulder Press',sets:3,reps:20},{name:'Abdominal',sets:3,reps:30}]},
  {id:'sl10',category:'hypertrophy',level:'advanced',name:'GVT - Volume Alem\u00E3o',days:'5x/semana',goal:'\uD83D\uDCAA Hipertrofia',exercises:[{name:'Supino',sets:10,reps:10},{name:'Remada',sets:10,reps:10},{name:'Agachamento',sets:10,reps:10},{name:'Shoulder Press',sets:4,reps:12},{name:'B\u00EDceps Curl',sets:3,reps:12},{name:'Tr\u00EDceps na Corda',sets:3,reps:12}]}
];
var CATEGORY_LABELS={all:'Todos',hypertrophy:'\uD83D\uDCAA Hipertrofia',loss:'\uD83D\uDD25 Emagrecimento',strength:'\uD83C\uDFCB\uFE0F For\u00E7a',endurance:'\uD83C\uDFC3 Resist\u00EAncia'};
var LEVEL_LABELS={beginner:'Iniciante',intermediate:'Intermedi\u00E1rio',advanced:'Avan\u00E7ado'};
var LEVEL_COLORS={beginner:'var(--green)',intermediate:'var(--orange)',advanced:'var(--red)'};
