
function renderSuggest(){
  var filtered=SUGGEST_FILTER==='all'?WORKOUT_LIBRARY:WORKOUT_LIBRARY.filter(function(w){return w.category===SUGGEST_FILTER;});
  var filterBtns=Object.entries(CATEGORY_LABELS).map(function(e){var active=SUGGEST_FILTER===e[0];return'<button onclick="SUGGEST_FILTER=\''+e[0]+'\';renderSuggest()" style="padding:7px 14px;border-radius:99px;border:1px solid '+(active?'var(--blue)':'var(--border)')+';background:'+(active?'var(--bluedim)':'var(--card)')+';color:'+(active?'var(--blue2)':'var(--txt2)')+';font-size:13px;font-weight:600;cursor:pointer;font-family:var(--fb);white-space:nowrap">'+e[1]+'</button>';}).join('');
  var cards=filtered.map(function(w){var already=getWorkouts().some(function(x){return x.name===w.name;});var exPreview=w.exercises.slice(0,4).map(function(e){return'<span class="badge">'+esc(e.name)+'</span>';}).join('');return'<div style="background:var(--card);border:1px solid var(--border);border-radius:var(--rl);padding:16px;margin-bottom:12px"><div style="font-weight:700;font-size:16px;margin-bottom:4px">'+esc(w.name)+'</div><div style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:8px"><span style="font-size:11px;background:var(--bluedim);color:var(--blue2);padding:2px 8px;border-radius:99px;font-weight:600">'+w.goal+'</span><span style="font-size:11px;background:rgba(255,255,255,0.05);color:'+LEVEL_COLORS[w.level]+';padding:2px 8px;border-radius:99px;font-weight:600">'+LEVEL_LABELS[w.level]+'</span><span style="font-size:11px;color:var(--muted)">\uD83D\uDCC5 '+w.days+'</span></div><div style="margin-bottom:12px">'+exPreview+(w.exercises.length>4?'<span style="font-size:11px;color:var(--muted)"> +'+(w.exercises.length-4)+' mais</span>':'')+'</div><div style="display:flex;gap:8px"><button onclick="previewSuggest(\''+w.id+'\')" class="btn btn-ghost btn-sm" style="flex:1">\uD83D\uDC41 Ver</button>'+(already?'<button class="btn btn-sm" style="flex:1;background:rgba(63,185,80,0.1);border:1px solid var(--green);color:var(--green);cursor:default">\u2705 Adicionado</button>':'<button onclick="addSuggestToMyWorkouts(\''+w.id+'\')" class="btn btn-blue btn-sm" style="flex:1">+ Adicionar</button>')+'</div></div>';}).join('');
  document.getElementById('suggest-body').innerHTML='<div style="display:flex;gap:8px;overflow-x:auto;padding-bottom:10px;margin-bottom:16px;scrollbar-width:none">'+filterBtns+'</div>'+cards+'<div style="background:var(--card);border:1px solid var(--blue);border-radius:var(--rl);padding:16px;margin-top:8px"><p style="font-weight:700;font-size:15px;margin-bottom:8px">\u270F\uFE0F Criar treino do zero</p><p style="font-size:13px;color:var(--txt2);margin-bottom:12px">Monte seu pr\u00F3prio treino personalizado.</p><button onclick="homeAddWorkout();showPage(\'home\')" class="btn btn-blue">+ Criar Treino Personalizado</button></div>';
}
function previewSuggest(id){var w=WORKOUT_LIBRARY.find(function(x){return x.id===id;});if(!w)return;var already=getWorkouts().some(function(x){return x.name===w.name;});openModal('<h2 style="font-family:var(--fd);font-size:24px;margin-bottom:4px">'+esc(w.name)+'</h2><p style="font-size:13px;color:var(--txt2);margin-bottom:16px">'+w.goal+' \u00B7 '+LEVEL_LABELS[w.level]+' \u00B7 '+w.days+'</p><div style="display:flex;flex-direction:column;gap:8px;margin-bottom:20px">'+w.exercises.map(function(ex,i){return'<div style="display:flex;align-items:center;gap:12px;padding:10px 12px;background:var(--bg);border-radius:var(--rs)"><span style="width:24px;height:24px;border-radius:50%;background:var(--bluedim);color:var(--blue2);display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:700;flex-shrink:0">'+(i+1)+'</span><span style="flex:1;font-weight:600;font-size:14px">'+esc(ex.name)+'</span><span style="font-size:13px;color:var(--muted)">'+ex.sets+'\u00D7'+ex.reps+'</span></div>';}).join('')+'</div>'+(already?'<button class="btn btn-ghost" style="opacity:0.6;cursor:default">\u2705 J\u00E1 adicionado</button>':'<button class="btn btn-blue" onclick="closeModal();addSuggestToMyWorkouts(\''+id+'\')">+ Adicionar ao Meu App</button>'));}
function addSuggestToMyWorkouts(id){var w=WORKOUT_LIBRARY.find(function(x){return x.id===id;});if(!w)return;var newW={id:uid(),name:w.name,exercises:w.exercises.map(function(e){return{id:uid(),name:e.name,sets:e.sets,reps:e.reps,weight:0};})};saveWorkouts(getWorkouts().concat([newW]));toast('\u2705 "'+w.name+'" adicionado!');renderSuggest();}

var THEMES=[
  {id:'dark',name:'Dark',emoji:'\uD83C\uDF11',bg:'#0d1117',bg2:'#161b22',card:'#1c2128',border:'#30363d',blue:'#4d94ff',blue2:'#58a6ff',bluedim:'rgba(77,148,255,0.12)',txt:'#e6edf3',txt2:'#8b949e',muted:'#484f58'},
  {id:'amoled',name:'AMOLED',emoji:'\u2B1B',bg:'#000000',bg2:'#0a0a0a',card:'#111111',border:'#222222',blue:'#4d94ff',blue2:'#58a6ff',bluedim:'rgba(77,148,255,0.1)',txt:'#ffffff',txt2:'#888888',muted:'#444444'},
  {id:'midnight',name:'Midnight',emoji:'\uD83C\uDF0C',bg:'#0a0015',bg2:'#12002a',card:'#1a0035',border:'#2d0060',blue:'#a371f7',blue2:'#c4b5fd',bluedim:'rgba(163,113,247,0.12)',txt:'#f0e8ff',txt2:'#9d7fcc',muted:'#4a3570'},
  {id:'forest',name:'Floresta',emoji:'\uD83C\uDF3F',bg:'#0a120a',bg2:'#0f1f0f',card:'#152415',border:'#1e3a1e',blue:'#3fb950',blue2:'#56d364',bluedim:'rgba(63,185,80,0.12)',txt:'#e8f5e8',txt2:'#7db87d',muted:'#3a5c3a'},
  {id:'fire',name:'Fogo',emoji:'\uD83D\uDD25',bg:'#110800',bg2:'#1a0f00',card:'#231500',border:'#3d2200',blue:'#ff7b00',blue2:'#ff9a3c',bluedim:'rgba(255,123,0,0.12)',txt:'#fff0e0',txt2:'#cc8844',muted:'#5c3d1a'},
  {id:'ocean',name:'Oceano',emoji:'\uD83C\uDF0A',bg:'#000d1a',bg2:'#001833',card:'#002244',border:'#003366',blue:'#2dd4bf',blue2:'#5eead4',bluedim:'rgba(45,212,191,0.12)',txt:'#e0f7f5',txt2:'#6bbfb5',muted:'#2a6b66'},
  {id:'rose',name:'Rosa',emoji:'\uD83C\uDF38',bg:'#120008',bg2:'#1e0012',card:'#2a001a',border:'#440028',blue:'#f472b6',blue2:'#f9a8d4',bluedim:'rgba(244,114,182,0.12)',txt:'#ffe8f4',txt2:'#c47a9a',muted:'#5c2a42'},
  {id:'light',name:'Claro',emoji:'\u2600\uFE0F',bg:'#f5f7fa',bg2:'#ffffff',card:'#ffffff',border:'#e1e5eb',blue:'#2563eb',blue2:'#3b82f6',bluedim:'rgba(37,99,235,0.1)',txt:'#111827',txt2:'#6b7280',muted:'#9ca3af'},
  {id:'neon',name:'Neon',emoji:'\u26A1',bg:'#050510',bg2:'#0a0a1e',card:'#0f0f28',border:'#1a1a40',blue:'#00f0ff',blue2:'#80f8ff',bluedim:'rgba(0,240,255,0.1)',txt:'#e0ffff',txt2:'#60c8cc',muted:'#2a4a4c'}
];
var FONTS=[{id:'Bebas Neue',name:'Bebas Neue',sample:'GYMTRACKER'},{id:'Space Grotesk',name:'Space Grotesk',sample:'GymTracker'},{id:'Georgia',name:'Georgia',sample:'GymTracker'},{id:'Impact',name:'Impact',sample:'GYMTRACKER'}];
function getCurrentThemeId(){return localStorage.getItem('gt_theme')||'dark';}
function applyTheme(themeId){var t=THEMES.find(function(x){return x.id===themeId;});if(!t)return;var root=document.documentElement;root.style.setProperty('--bg',t.bg);root.style.setProperty('--bg2',t.bg2);root.style.setProperty('--card',t.card);root.style.setProperty('--border',t.border);root.style.setProperty('--blue',t.blue);root.style.setProperty('--blue2',t.blue2);root.style.setProperty('--bluedim',t.bluedim);root.style.setProperty('--txt',t.txt);root.style.setProperty('--txt2',t.txt2);root.style.setProperty('--muted',t.muted);localStorage.setItem('gt_theme',themeId);}
function applyFont(fontId){document.documentElement.style.setProperty('--fd',"'"+fontId+"', sans-serif");localStorage.setItem('gt_font',fontId);}
function applyCustomColor(variable,value){document.documentElement.style.setProperty(variable,value);var custom=JSON.parse(localStorage.getItem('gt_custom_colors')||'{}');custom[variable]=value;localStorage.setItem('gt_custom_colors',JSON.stringify(custom));}
function loadSavedTheme(){var tid=localStorage.getItem('gt_theme');if(tid)applyTheme(tid);var fid=localStorage.getItem('gt_font');if(fid)applyFont(fid);try{var custom=JSON.parse(localStorage.getItem('gt_custom_colors')||'{}');Object.entries(custom).forEach(function(e){document.documentElement.style.setProperty(e[0],e[1]);});}catch(e){}}
function openThemePicker(){
  var currentId=getCurrentThemeId(),currentFont=localStorage.getItem('gt_font')||'Bebas Neue';
  var themeGrid=THEMES.map(function(t){var active=currentId===t.id;return'<button onclick="applyTheme(\''+t.id+'\');openThemePicker()" style="display:flex;flex-direction:column;align-items:center;gap:6px;padding:12px 6px;border-radius:var(--r);border:2px solid '+(active?t.blue:'var(--border)')+';background:'+t.bg2+';cursor:pointer;font-family:var(--fb)"><div style="display:flex;gap:3px"><div style="width:14px;height:14px;border-radius:50%;background:'+t.bg+'"></div><div style="width:14px;height:14px;border-radius:50%;background:'+t.blue+'"></div><div style="width:14px;height:14px;border-radius:50%;background:'+t.txt+'"></div></div><span style="font-size:16px">'+t.emoji+'</span><span style="font-size:11px;font-weight:600;color:'+t.txt2+'">'+t.name+'</span>'+(active?'<div style="width:16px;height:16px;border-radius:50%;background:'+t.blue+';display:flex;align-items:center;justify-content:center;font-size:10px">\u2713</div>':'')+'</button>';}).join('');
  var fontBtns=FONTS.map(function(f){var active=currentFont===f.id;return'<button onclick="applyFont(\''+f.id+'\');openThemePicker()" style="flex:1;padding:10px 6px;border-radius:var(--r);border:2px solid '+(active?'var(--blue)':'var(--border)')+';background:'+(active?'var(--bluedim)':'var(--card)')+';cursor:pointer;font-family:var(--fb);font-size:11px;font-weight:600;color:'+(active?'var(--blue2)':'var(--txt2)')+'"><div style="font-family:\''+f.id+'\',sans-serif;font-size:16px;margin-bottom:2px;color:var(--txt)">'+f.sample+'</div>'+f.name+'</button>';}).join('');
  var curAccent=getComputedStyle(document.documentElement).getPropertyValue('--blue').trim()||'#4d94ff';
  var curBg=getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()||'#0d1117';
  var curCard=getComputedStyle(document.documentElement).getPropertyValue('--card').trim()||'#1c2128';
  openModal('<h2 style="font-family:var(--fd);font-size:26px;margin-bottom:4px">\uD83C\uDFA8 Personalizar Tema</h2><p style="font-size:13px;color:var(--txt2);margin-bottom:16px">Escolha um tema ou crie o seu</p><p class="lbl" style="margin-bottom:10px">Temas Prontos</p><div style="display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:20px">'+themeGrid+'</div><p class="lbl" style="margin-bottom:10px">Fonte do T\u00EDtulo</p><div style="display:flex;gap:8px;margin-bottom:20px;flex-wrap:wrap">'+fontBtns+'</div><p class="lbl" style="margin-bottom:10px">Cores Personalizadas</p><div style="display:flex;flex-direction:column;gap:10px;margin-bottom:20px"><div style="display:flex;align-items:center;justify-content:space-between;padding:10px 14px;background:var(--bg);border-radius:var(--rs);border:1px solid var(--border)"><div><div style="font-weight:600;font-size:14px">Cor de Destaque</div></div><input type="color" value="'+curAccent.replace(/ /g,'')+'" onchange="applyCustomColor(\'--blue\',this.value);applyCustomColor(\'--blue2\',this.value)" style="width:44px;height:36px;border:none;border-radius:8px;cursor:pointer;background:none;padding:2px"/></div><div style="display:flex;align-items:center;justify-content:space-between;padding:10px 14px;background:var(--bg);border-radius:var(--rs);border:1px solid var(--border)"><div><div style="font-weight:600;font-size:14px">Fundo Principal</div></div><input type="color" value="'+curBg.replace(/ /g,'')+'" onchange="applyCustomColor(\'--bg\',this.value)" style="width:44px;height:36px;border:none;border-radius:8px;cursor:pointer;background:none;padding:2px"/></div></div><button onclick="resetTheme();closeModal()" class="btn btn-ghost" style="font-size:13px">\u21A9 Restaurar padr\u00E3o</button>');
}
function resetTheme(){localStorage.removeItem('gt_theme');localStorage.removeItem('gt_font');localStorage.removeItem('gt_custom_colors');['--bg','--bg2','--card','--border','--blue','--blue2','--bluedim','--txt','--txt2','--muted','--fd'].forEach(function(v){document.documentElement.style.removeProperty(v);});toast('\u21A9 Tema restaurado!');}

// ===== BOOT =====
loadSavedTheme();
authRenderUsersList();

(function(){
  var saved=localStorage.getItem('gt_session');
  if(saved){
    var users=authGetUsers();
    if(users.find(function(u){return u.username===saved;})){
      authStartSession(saved);
      return;
    }
  }
  // No valid session - show auth screen (already visible by default)
})();

fetch('exercise_imgs.json')
  .then(function(r){return r.json();})
  .then(function(data){Object.assign(EXERCISE_IMGS,data);EXSUGG=Object.keys(EXERCISE_IMGS).sort();})
  .catch(function(e){console.log('imgs:',e);});